package mi.domain.enumok;

public enum FonevRag {
    TOBBES_SZAM,
    TARGY,
    BIRTOKOS_EGYES_SZAM_ELSO_SZEMELY,
    BIRTOKOS_EGYES_SZAM_MASODIK_SZEMELY,
    BIRTOKOS_EGYES_SZAM_HARMADIK_SZEMELY,
    BIRTOKOS_TOBBES_SZAM_ELSO_SZEMELY,
    BIRTOKOS_TOBBES_SZAM_MASODIK_SZEMELY,
    BIRTOKOS_TOBBES_SZAM_HARMADIK_SZEMELY,
    HELY
}
