package mi.domain.enumok;

public enum SzamSzemely {
    EGYES_SZAM_ELSO_SZEMELY,
    EGYES_SZAM_MASODIK_SZEMELY,
    EGYES_SZAM_HARMADIK_SZEMELY,
    TOBBES_SZAM_ELSO_SZEMELY,
    TOBBES_SZAM_MASODIK_SZEMELY,
    TOBBES_SZAM_HARMADIK_SZEMELY
}
